Repository ethereumbook/ethereumbook, pull requests merged in 2018-04, with the labels that each got.

#374 lightweight clients: mobile wallets, browser wallets
  clients.asciidoc
Labels: in progress

#377 Early release
  book.asciidoc
  preface.asciidoc
  standards-eip-erc.asciidoc
Labels: in progress

#378 added appendixes to early release
  appdx-standards-eip-erc.asciidoc
  book.asciidoc
Labels: in progress

#393 moved ganache from dev-tools to ethereum-testnets
  dev-tools.asciidoc
  ethereum-testnets.asciidoc
Labels: in progress

#392 Four stages of Ethereum: Frontier, Homestead, Metropolis, Serenity
  what-is.asciidoc
Labels: in progress

#406 glossary: few terms from intro, wallets, keys chapters
  glossary.asciidoc
  preface.asciidoc
Labels: in progress

#405 Glossary: No new entries, some additions to definitions, few word replacements/suggestions.
  clients.asciidoc
  glossary.asciidoc
Labels: in progress

#426 anchors: few chapters
  tokens.asciidoc
  transactions.asciidoc
  wallets.asciidoc
  what-is.asciidoc
Labels: in progress

#428 glossary: definitions for difficulty, hard fork, and LevelDB
  glossary.asciidoc
Labels: in progress

#419 Add Auction Dapp
  code/auction_dapp/.gitignore
  code/auction_dapp/DEV_README.md
  code/auction_dapp/README.md
  code/auction_dapp/auction_diagram.png
  code/auction_dapp/backend/.gitignore
  code/auction_dapp/backend/contracts/AuctionRepository.sol
  code/auction_dapp/backend/contracts/DeedRepository.sol
  code/auction_dapp/backend/contracts/ERC721/DeprecatedERC721.sol
  code/auction_dapp/backend/contracts/ERC721/ERC721.sol
  code/auction_dapp/backend/contracts/ERC721/ERC721Basic.sol
  code/auction_dapp/backend/contracts/ERC721/ERC721BasicToken.sol
  code/auction_dapp/backend/contracts/ERC721/ERC721Holder.sol
  code/auction_dapp/backend/contracts/ERC721/ERC721Receiver.sol
  code/auction_dapp/backend/contracts/ERC721/ERC721Token.sol
  code/auction_dapp/backend/contracts/Migrations.sol
  code/auction_dapp/backend/contracts/utils/AddressUtils.sol
  code/auction_dapp/backend/contracts/utils/math/Math.sol
  code/auction_dapp/backend/contracts/utils/math/SafeMath.sol
  code/auction_dapp/backend/migrations/1_initial_migration.js
  code/auction_dapp/backend/migrations/2_deploy_contracts.js
  code/auction_dapp/backend/scripts/prepare.js
  code/auction_dapp/backend/test/1_auctionrepository.js
  code/auction_dapp/backend/test/2_deedrepository.js
  code/auction_dapp/backend/test/output.address
  code/auction_dapp/backend/truffle-config.js
  code/auction_dapp/backend/truffle.js
  code/auction_dapp/frontend/.babelrc
  code/auction_dapp/frontend/.editorconfig
  code/auction_dapp/frontend/.gitignore
  code/auction_dapp/frontend/.postcssrc.js
  code/auction_dapp/frontend/README.md
  code/auction_dapp/frontend/config/dev.env.js
  code/auction_dapp/frontend/config/index.js
  code/auction_dapp/frontend/config/prod.env.js
  code/auction_dapp/frontend/index.html
  code/auction_dapp/frontend/src/App.vue
  code/auction_dapp/frontend/src/components/Auction.vue
  code/auction_dapp/frontend/src/components/Home.vue
  code/auction_dapp/frontend/src/config.js
  code/auction_dapp/frontend/src/contracts/AuctionRepository.json
  code/auction_dapp/frontend/src/contracts/DeedRepository.json
  code/auction_dapp/frontend/src/main.js
  code/auction_dapp/frontend/src/models/AuctionRepository.js
  code/auction_dapp/frontend/src/models/ChatRoom.js
  code/auction_dapp/frontend/src/models/DeedRepository.js
  code/auction_dapp/frontend/src/router/index.js
  code/auction_dapp/frontend/static/.gitkeep
Labels: in progress, priority

#443 Moved oracles and vyper into main, updated README
  README.md
  oracles.asciidoc
  vyper.asciidoc
Labels: in progress

#447 Ethereum Name Service: intro, outline and links
  ens.asciidoc
  images/ens-checkname.png
Labels: in progress

#471 contribution notes proposals
  CONTRIBUTE.md
Labels: in progress

#473 fixing, adding difs on glossary
  glossary.asciidoc
Labels: in progress

#488 Update ethereum-testnets.asciidoc
  ethereum-testnets.asciidoc
Labels: in progress

#481 DAO fork history and differences between Ethereum and Ethereum Classic
  contrib/forks-history.asciidoc
Labels: in progress, review needed

#523 upgradability patterns
  contrib/upgradability-patterns.asciidoc
  images/proxy-lib.png
Labels: in progress
